"""Add apollo_searched column to organization_enrichments

Revision ID: f2b8012a9cf6
Revises: c19135e4e60d
Create Date: 2025-09-16 09:53:31.926151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b8012a9cf6'
down_revision: Union[str, None] = 'c19135e4e60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_enrichments', sa.Column('apollo_searched', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_enrichments', 'apollo_searched')
    # ### end Alembic commands ###
